In [264]:
#question 1
def change_char(str1):
    char = str1[0]
    str1 = str1.replace(char, '$')
    str1 = char + str1[1:]
    return str1
print(change_char('prospect'))

pros$ect


In [34]:
#question 2
def chars_mix_up(a, b):
    new_a = b[:2] + a[2:]
    new_b = a[:2] + b[2:]
    return new_a + ' ' + new_b

print(chars_mix_up('abc', 'xyz'))

xyc abz


In [41]:
#question 3
def sample(str1):
    k=str1
    a=len(str1)
    if a>=3:
        if k[3:]=='ing':
            return k + 'ly'
        else:
            return k +'ing'
    else:
        return 'Length is less than 3'

print(sample('a'))

Length is less than 3


In [50]:
#question 4
def not_poor(str1):
    snot = str1.find('not')
    spoor = str1.find('poor')
    print(snot,spoor)
    if spoor > snot and snot>0 and spoor>0:
        str1 = str1.replace(str1[snot:(spoor+4)], 'good')
        return str1
    else:
        return str1
    
print(not_poor('The lyrics is not that poor!'))
#print(not_poor('The lyrics is poor!'))

14 23
The lyrics is good!


In [67]:
def oddindex(str1):
    str1=str1[::-1]
    str1=str1[::2]
    str1=str1[::-1]
    return str1

print(oddindex('string'))

tig


In [69]:
#question 5
def odd_values_string(str):
    result = ""
    for i in range(len(str)):
        if i % 2 == 0:
            result = result + str[i]
            return result
        
print(odd_values_string('abcdef'))
print(odd_values_string('python'))

a
p


In [71]:
#question 6
def insert_end(str):
    sub_str = str[-2:]
    return sub_str*4
print(insert_end('Python'))
print(insert_end('Exercises'))

onononon
eseseses


In [74]:
#question 8
def start(str):
    k=len(str)
    if k>=3:
        sub_str = str[0:3]
        return sub_str 
    else:
        return 'Inavlid'
print(start('Py'))

Inavlid


In [77]:
#question 9
x = 3.1415926
y = 12.9999
print("\nOriginal Number: ", x)
print("Formatted Number: "+"{:.2f}".format(x));
print("Original Number: ", y)
print("Formatted Number: "+"{:.2f}".format(y));
print()


Original Number:  3.1415926
Formatted Number: 3.14
Original Number:  12.9999
Formatted Number: 13.00



In [123]:

#question 10
def substring(k):
    str="Machine Learning is undeniably one of the most influential and powerful technologies in today’s world. More importantly, we are far from seeing its full potential. There’s no doubt, it will continue to be making headlines for the foreseeable future. This article is designed as an introduction to the Machine Learning concepts, covering all the fundamental ideas without being too high level."
    l=str.count(k)
    return l
    
print(substring("the"))

4


In [268]:
#question 11
import collections
str1 = 'thequickbrownfoxjumpsoverthelazydog'
d = collections.defaultdict(int)
for c in str1: 
    d[c] += 1
for c in sorted(d, key=d.get, reverse=True):
    if d[c] > 1:
        print('%s %d' % (c, d[c]))

o 4
e 3
t 2
h 2
u 2
r 2


In [107]:
#question 12
area = 1256.66
volume = 1254.725
decimals = 2
print("The area of the rectangle is {0:.{1}f}cm\u00b2".format(area, decimals))
decimals = 3
print("The volume of the cylinder is {0:.{1}f}cm\u00b3".format(volume,
decimals))

The area of the rectangle is 1256.66cm²
The volume of the cylinder is 1254.725cm³


In [137]:
#question 13
import string
alphabet = set(string.ascii_lowercase)
print(alphabet)

input_string = 'The quick brown fox jumps over the lazy dog'
l=set(input_string.lower())
print(l)
print(set(input_string.lower()) >= alphabet)

input_string = 'The quick brown fox jumps over the lazy cat'
print(set(input_string.lower()) >= alphabet)
print(len(input_string)-8)

{'m', 'k', 'b', 'g', 'l', 'c', 'o', 'p', 'f', 'j', 'w', 'y', 's', 'd', 'z', 'q', 'a', 'h', 'u', 'r', 't', 'i', 'n', 'x', 'v', 'e'}
{'m', 'k', 'b', 'g', 'l', 'c', 'o', 'p', 'f', 'j', 'w', 'y', 's', 'z', 'd', 'q', 'a', 'h', 'u', 'r', ' ', 't', 'i', 'n', 'x', 'v', 'e'}
True
False
35


In [5]:
#question 15
def word_count(str):
    counts = dict()
    words = str.split()
    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1
            counts_x = sorted(counts.items(), key=lambda kv: kv[1])
            #print(counts_x)
    return counts_x[-1]

print(word_count("Both of these issues are fixed by postponing the evaluation of annotations. Instead of compiling code which executes expressions in annotations at their definition time, the compiler stores the annotation in a string form equivalent to the AST of the expression in question. If needed, annotations can be resolved at runtime using typing.get_type_hints(). In the common case where this is not required, the annotations are cheaper to store (since short strings are interned by the interpreter) and make startup time faster."))

('the', 8)


In [33]:
#question 17
from itertools import combinations
def lowerstr(str,l):
    k=set(str)
    m=list(combinations(k,l))
    return len(m)
    

print(lowerstr("wolf",3))

4


In [ ]:
#question 18
def number_of_substrings(str):
    str_len = len(str);
    return int(str_len * (str_len + 1) / 2);

str1 = input("Input a string: ")
print("Number of substrings:")
print(number_of_substrings(str1))

In [6]:
#question 20
def match_words(words):
    ctr = 0
    for word in words:
        if len(word) > 1 and word[0] == word[-1]:
            ctr += 1
    return ctr
print(match_words(['abc', 'xyz', 'aba', '1221']))

xyz
2


In [27]:
#question 21
def last(n): 
    return n[-1]


def incrlast(list1):
    return sorted(list1,key=last)

    
    
    
print(incrlast([(3,5),(6,1),(2,2),(3,3)]))

[(6, 1), (2, 2), (3, 3), (3, 5)]


In [31]:
#question 22
def remove_duplicate(list1):
    list2=set(list1)
    l=list(list2)
    return l

print(remove_duplicate([2,2,3,4,5,6,5,3,5,7]))

[2, 3, 4, 5, 6, 7]


In [37]:
#question 23
def long(n,list1):
    word=[]
    l=list1.split('')
    for i in range(len(l)):
        if(l[i]>n):
            word.append(l[i])
    return word

print(long_words(4, "The quick brown fox jumps over the lazy dog"))

['quick', 'brown', 'jumps']


In [53]:
#question 24

def removelist(list1):
    k=[x for (i,x) in enumerate(list1) if i not in (0,4,5)]
    return k

print(removelist(['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']))

['Green', 'White', 'Black']


In [55]:
#question 25
import itertools
print(list(itertools.permutations([5,3,8])))

[(5, 3, 8), (5, 8, 3), (3, 5, 8), (3, 8, 5), (8, 5, 3), (8, 3, 5)]


In [101]:
#question 26
def sorteduniq(tuple1):
    m=[]
    k=tuple1[0]
    l=list(k)
    return l
    
    

print(sorteduniq( [ (1, 2), (3, 4), (1, 2), (5, 6), (7, 8), (1, 2), (3, 4), (3, 4), (7, 8), (9, 10) ]))

[1, 2]


In [ ]:
#question 27
class py_solution:
    def int_to_Roman(self, num):


        val = [
1000, 900, 500, 400,
100, 90, 50, 40,
10, 9, 5, 4,
1]
        syb = [
"M", "CM", "D", "CD",
"C", "XC", "L", "XL",
"X", "IX", "V", "IV",
"I"
]
        roman_num = ''
        i = 0
        while num > 0:
            for _ in range(num // val[i]):
                roman_num += syb[i]
                num -= val[i]
                i += 1
        return roman_num

print(py_solution().int_to_Roman(1))
print(py_solution().int_to_Roman(4000))

In [1]:
#problem 29

class py_solution:
    def is_valid_parenthese(self, str1):
        stack, pchar = [], {"(": ")", "{": "}", "[": "]"}
        for parenthese in str1:
            if parenthese in pchar:
                stack.append(parenthese)
            elif len(stack) == 0 or pchar[stack.pop()] != parenthese:
                return False
        return len(stack) == 0

print(py_solution().is_valid_parenthese("(){}[]"))
print(py_solution().is_valid_parenthese("()[{)}"))
print(py_solution().is_valid_parenthese("()"))

True
False
True


In [13]:
#problem 31
def fucn(list1,n):
    l=[]
    l=list1
    for i in range(len(l)):
        for j in range(len(l)):
            if(l[i]+l[j]==n):
                return i,j
                
print(fucn([10,20,10,40,50,60,70],70))
    

(0, 5)


In [24]:
#problem 32
def func(list1):
    l=[]
    l=list1
    k=0
    for i in range(len(list1)):
        for j in range(len(list1)):
            for k in range(len(list1)):
                if(l[i]+l[j]+l[k]==0):
                    print((l[i],l[j],l[k]))

print(func( [-25, -10, -7, -3, 2, 4, 8, 10]))

(-10, 2, 8)
(-10, 8, 2)
(-7, -3, 10)
(-7, 10, -3)
(-3, -7, 10)
(-3, 10, -7)
(2, -10, 8)
(2, 8, -10)
(8, -10, 2)
(8, 2, -10)
(10, -7, -3)
(10, -3, -7)
None


In [28]:
#problem 33
class py_solution:
    def pow(self, x, n):
        if x==0 or x==1 or n==1:
            return x 
        if x==-1:
            if n%2 ==0:
                return 1
            else:
                return -1
            if n==0:
                return 1
            if n<0:
                return 1/self.pow(x,-n)
            val = self.pow(x,n//2)
            if n%2 ==0:
                return val*val
            return val*val*x
        
print(py_solution().pow(2, -3));
print(py_solution().pow(3, 5));
print(py_solution().pow(100, 0));

None
None
None


In [30]:
class solution:
    def __init__(self):
        self.str1 = ""
    def get_String(self):
        self.str1 = input()
    def print_String(self):
        print(self.str1.upper())
            
str1 = solution()
str1.get_String()
str1.print_String()      

jnsgksgs
JNSGKSGS


In [6]:
#problem 35
class rectangle():
    
    def __init__(self,l,b):
        self.length=l
        self.breadth=b
        
    def area(self):
        return self.breadth*self.length
    
print(rectangle(20,30).area())

600


In [14]:
#problem 36
class circle():
    def __init__(self, r):
        self.radius = r
        
    def area(self):
        print("Area is:")
        return 3.14*self.radius*self.radius
    
    def perimeter(self):
        print("Perimeter is:")
        return 2*3.14*self.radius
    
    
print(circle(8).area())
print(circle(8).perimeter())

Area is:
200.96
Perimeter is:
50.24


In [15]:
#question 37
import itertools
x = itertools.cycle('ABCD')
print(type(x).__name__)

cycle


In [19]:
from collections import Counter
classes = (
('V', 1),
('VI', 1),
('V', 2),
('VI', 2),
('VI', 3),
('VII', 1),
)
students = Counter(class_name for class_name, no_students in classes)
print(students)

Counter({'VI': 3, 'V': 2, 'VII': 1})


In [26]:
#question 39
from collections import OrderedDict
dict = {'Afghanistan': 93, 'Albania': 355, 'Algeria': 213, 'Andorra':
376, 'Angola': 244}
new_dict = OrderedDict(dict.items())
for key in reversed(new_dict):
    print (key, new_dict[key])

Angola 244
Andorra 376
Algeria 213
Albania 355
Afghanistan 93


In [27]:
#question 40
from collections import Counter
def compare_lists(x, y):
    return Counter(x) == Counter(y)
n1 = [20, 10, 30, 10, 20, 30]
n2 = [30, 20, 10, 30, 20, 50]
print(compare_lists(n1, n2))

False


In [28]:
#question 41
from array import array
a = array("I", (12,25))
print("Array buffer start address in memory and number of elements.")
print(a.buffer_info())

Array buffer start address in memory and number of elements.
(2435695258688, 2)


In [29]:
#problem 42
import array
import binascii
a = array.array('i', [1,2,3,4,5,6])
print("Original array:")
print('A1:', a)
bytes_array = a.tobytes()
print('Array of bytes:', binascii.hexlify(bytes_array))

Original array:
A1: array('i', [1, 2, 3, 4, 5, 6])
Array of bytes: b'010000000200000003000000040000000500000006000000'


In [30]:
#problem 43
import array
import binascii
a = array.array('i', [1,2,3,4,5,6])
print("Original array:")
print('A1:', a)
bytes_array = a.tobytes()
print('Array of bytes:', binascii.hexlify(bytes_array))

Original array:
A1: array('i', [1, 2, 3, 4, 5, 6])
Array of bytes: b'010000000200000003000000040000000500000006000000'


In [31]:
#problem 44
from array import array
import binascii
array1 = array('i', [7, 8, 9, 10])
print('array1:', array1)
as_bytes = array1.tobytes()
print('Bytes:', binascii.hexlify(as_bytes))
array2 = array('i')
array2.frombytes(as_bytes)
print('array2:', array2)

array1: array('i', [7, 8, 9, 10])
Bytes: b'0700000008000000090000000a000000'
array2: array('i', [7, 8, 9, 10])


In [33]:
#question 45
import heapq
heap = []
heapq.heappush(heap, ('V', 3))
heapq.heappush(heap, ('V', 2))
heapq.heappush(heap, ('V', 1))
print("Items in the heap:")
for a in heap:
    print(a)
    print("The smallest item in the heap:")
    print(heap[0])
    print("Pop the smallest item in the heap:")
    heapq.heappop(heap)
for a in heap:
    print(a)

Items in the heap:
('V', 1)
The smallest item in the heap:
('V', 1)
Pop the smallest item in the heap:
('V', 3)
The smallest item in the heap:
('V', 2)
Pop the smallest item in the heap:
('V', 3)


In [269]:
#question 47
def harmonic_sum(n):
    if n < 2:
        return 1
    else:
        return 1 / n + (harmonic_sum(n - 1))
print(harmonic_sum(7))
print(harmonic_sum(4))

2.5928571428571425
2.083333333333333


In [270]:
#question 48
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [271]:
#question 49
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [272]:
#question 50
import numpy as np
# Create an empty array
x = np.empty((3,4))
print(x)
# Create a full array
y = np.full((3,3),6)
print(y)
51. 
import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in Centigrade degrees:")
print(5*F/9 - 5*32/9)

[[0.96666667 0.93181818 0.41666667 0.97058824]
 [0.90625    0.61666667 0.42553191 0.27777778]
 [0.18072289 0.33333333 0.09722222 0.12121212]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]
Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [273]:
#question 52
import numpy as np
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print("Original array:x ",x)
print("Original array:y ",y)
print("Real part of the array:")
print(x.real)
print(y.real)
print("Imaginary part of the array:")
print(x.imag)
print(y.imag)

Original array:x  [1.+0.j]
Original array:y  [0.70710678+0.70710678j]
Real part of the array:
[1.]
[0.70710678]
Imaginary part of the array:
[0.]
[0.70710678]


In [274]:
#question 53
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [0, 40]
print("Array2: ",array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


In [275]:
#question 54
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [276]:
#question 55
import numpy as np
x = np.array([10, 10, 20, 20, 30, 30])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))
x = np.array([[1, 1], [2, 3]])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


In [277]:
#question 56
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


In [278]:
#question 57
import numpy as np
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


In [282]:
#question 58
import numpy as np
print(np.any([[False,False],[False,False]]))
print(np.any([[True,True],[True,True]]))
print(np.any([10, 20, 0, -50]))
print(np.any([10, 20, -50]))

False
True
True
True


In [283]:
#question 59
import numpy as np
a = [1, 2, 3, 4]
print("Original array")
print(a)
print("Repeating 2 times")
x = np.tile(a, 2)
print(x)
print("Repeating 3 times")
x = np.tile(a, 3)
print(x)

Original array
[1, 2, 3, 4]
Repeating 2 times
[1 2 3 4 1 2 3 4]
Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]


In [284]:
#question 60
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array: ",x)
print("Maximum Values: ",np.argmax(x))
print("Minimum Values: ",np.argmin(x))

Original array:  [1 2 3 4 5 6]
Maximum Values:  5
Minimum Values:  0


In [285]:
#question 61
import numpy as np
a = np.array([1, 2])
b = np.array([4, 5])
print("Array a: ",a)
print("Array b: ",b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))

Array a:  [1 2]
Array b:  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


In [286]:
#question 62
import numpy as np
a = np.array([[4, 6],[2, 1]])
print("Original array: ")
print(a)
print("Sort along the first axis: ")
x = np.sort(a, axis=0)
print(x)
print("Sort along the last axis: ")
y = np.sort(x, axis=1)
print(y)

Original array: 
[[4 6]
 [2 1]]
Sort along the first axis: 
[[2 1]
 [4 6]]
Sort along the last axis: 
[[1 2]
 [4 6]]


In [287]:
#question 63
import numpy as np
first_names = ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)

[1 3 2 4 0]


In [288]:
#question 64
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [289]:
#question 65
import numpy as np
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


In [290]:
#question 66
import numpy as np
print("Create an array of zeros")
x = np.zeros((1,2))
print("Default type is float")
print(x)
print("Type changes to int")
x = np.zeros((1,2), dtype = np.int)
print(x)
print("Create an array of ones")
y= np.ones((1,2))
print("Default type is float")
print(y)
print("Type changes to int")
y = np.ones((1,2), dtype = np.int)
print(y)

Create an array of zeros
Default type is float
[[0. 0.]]
Type changes to int
[[0 0]]
Create an array of ones
Default type is float
[[1. 1.]]
Type changes to int
[[1 1]]


In [291]:
#question 67
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print("6 rows and 0 columns")
print(x.shape)
y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 rows and 3 columns ")
print(y)
x = np.array([1,2,3,4,5,6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
x.shape = (3, 3)
print(x)

6 rows and 0 columns
(6,)
(3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [292]:
#question 68
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
y = np.reshape(x,(3,2))
print("Reshape 3x2:")
print(y)
z = np.reshape(x,(2,3))
print("Reshape 2x3:")
print(z)

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


In [293]:
#problem 101
import pandas as pd
d1=pd.Series([21,22,23,56,89])
d2=pd.Series([40,32,56,78,90])
print("Add two series")
k=d1+d2
print(k)
print("Subtact two series")
k=d1-d2
print(k)
print("Multipy two series")
k=d1*d2
print(k)
print("Divide two series")
k=d1/d2
print(k)


Add two series
0     61
1     54
2     79
3    134
4    179
dtype: int64
Subtact two series
0   -19
1   -10
2   -33
3   -22
4    -1
dtype: int64
Multipy two series
0     840
1     704
2    1288
3    4368
4    8010
dtype: int64
Divide two series
0    0.525000
1    0.687500
2    0.410714
3    0.717949
4    0.988889
dtype: float64


In [11]:
#question 102
import pandas as pd
k={'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
l=pd.Series(k)
print(l)

a    100
b    200
c    300
d    400
e    800
dtype: int64


In [23]:
#question 103
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1,errors='coerce',downcast='float')
print(s2)

0       100
1       200
2    python
3    300.12
4       400
dtype: object
Change the said data type to numeric:
0    100.000000
1    200.000000
2           NaN
3    300.119995
4    400.000000
dtype: float32


In [36]:
#question 104
import pandas as pd
d= {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
d1=pd.DataFrame(d)
print(d1)
print('First column:')
s1=d1.ix[:,0]
print(s1)

   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11
First column:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


C:\Users\omkar\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  import sys


In [42]:
#question 105
import pandas as pd
d=[1,2,3,4,5,6,7,8,9,5,3]
d1=pd.DataFrame(d)
print(d1)
mean=d1.mean()
print("Mean is")
print(mean)
Std=d1.std()
print("Standard deviation is")
print(Std)

    0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9   5
10  3
Mean is
0    4.818182
dtype: float64
Standard deviation is
0    2.522625
dtype: float64


In [43]:
#question 106
import pandas as pd
d={'X ':[78,85,96,80,86], ' Y ':[84,94,89,83,86],'Z':[86,97,96,72,83]}
d1=pd.DataFrame(d)
d1


X    Y    Z
0  78   84  86
1  85   94  97
2  96   89  96
3  80   83  72
4  86   86  83

In [54]:
#question 107
import numpy as np
import pandas as pd
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': [ 'yes', 'no', 'yes' , 'no', ' no ', ' yes ', 'yes', 'no', 'no', 'yes' ] }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j' ]
d1=pd.DataFrame(exam_data,index=labels)
print(d1)
print("The first 3 rows are:")
k=d1.iloc[:3]
print(k)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2     no 
f    Michael   20.0         3    yes 
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
The first 3 rows are:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


In [63]:
#question 108
import pandas as pd
import numpy as np

exam_data = {'name ': [ 'Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts' : [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify' : ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'] }
labels = ['a ', ' b ', ' c ', ' d ', ' e ', ' f ', ' g ', 'h', 'i', 'j']
d1=pd.DataFrame(exam_data,index=labels)
k=d1.iloc[[1, 3, 5, 6],[1,3]]
print(k)

     score qualify
 b     9.0      no
 d     NaN      no
 f    20.0     yes
 g    14.5     yes


In [76]:
#question 109
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 
                      'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', ' yes ', ' no ', ' no ', ' yes ', ' yes ', ' no ', ' no ', ' yes '] }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
d1=pd.DataFrame(exam_data,index=labels)
d=d1.ix[:,1]
print(d)
k=d.mean()
print("The mean is:")
print(k)

a    12.5
b     9.0
c    16.5
d     NaN
e     9.0
f    20.0
g    14.5
h     NaN
i     8.0
j    19.0
Name: score, dtype: float64
The mean is:
13.5625


C:\Users\omkar\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  # This is added back by InteractiveShellApp.init_path()


In [85]:
#question 110
import pandas as pd
d = {'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}
d1=pd.DataFrame(d)
print("original Data")
print(d1)
print("Renamed Data")
k=d1.rename(columns={'col1':'Column 1','col2':'Column 2','col3':'Column 3'})
print(k)


original Data
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
Renamed Data
   Column 1  Column 2  Column 3
0         1         4         7
1         2         5         8
2         3         6         9


In [94]:
#question 111
import pandas as pd
d1 = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily','Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
                   'city': ['California', 'Los Angeles', 'California', 'California', 'California', 'Los Angeles', 'Los Angeles', 'Georgia', 'Georgia', 'Los Angeles']})
k= d1.groupby(["city"]).size().reset_index(name='Number of people')
print(k)

          city  Number of people
0   California                 4
1      Georgia                 2
2  Los Angeles                 4


In [104]:
#question 112
import pandas as pd
import numpy as np
d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}
df = pd.DataFrame(data=d)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
print("Original DataFrame")
print(df)

Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1


In [110]:
#question 113
import pandas as pd
d1=pd.Series(['3/11/2000', '3/12/2000', '3/13/2000'])
print("Original series")
print(d1)
d = pd.to_datetime(pd.Series(['3/11/2000', '3/12/2000', '3/13/2000']))
print(d)

Original series
0    3/11/2000
1    3/12/2000
2    3/13/2000
dtype: object
0   2000-03-11
1   2000-03-12
2   2000-03-13
dtype: datetime64[ns]


In [112]:
#question 114
import pandas as pd
d = pd.DataFrame()
d1 = pd.DataFrame({"col1": range(3),"col2": range(3)})
d = d.append(d1)
print(d)

   col1  col2
0     0     0
1     1     1
2     2     2


In [117]:
#question 115
import pandas as pd
d = {'col1': [1, 2, 3, 4, 7], 'col2': [4, 5, 6, 9, 5], 'col3': [7, 8, 12, 1, 11]}
d1=pd.DataFrame(d)
print(d1)
k=len(d1.columns)
print("The number of columns are:")
print(k)

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11
The number of columns are:
3


In [121]:
#question 116
import pandas as pd
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(data=d)
k=df.drop([3,4,5])
print(k)
l=df.iloc[:3]
print(l)

   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8


In [136]:
#question 117
import pandas as pd
df=pd.read_excel('C:\\Users\\omkar\\Downloads\\coalpublic2013.xlsx')
print(df)

    Year  MSHA ID                       Mine_Name  Production  Labor_Hours
0   2013   103381            Tacoa Highwall Miner       56004        22392
1   2013   103404                Reid School Mine       28807        28447
2   2013   100759  North River #1 Underground Min     1440115       474784
3   2013   103246                      Bear Creek       87587        29193
4   2013   103451                     Knight Mine      147499        46393
5   2013   103433              Crane Central Mine       69339        47195
6   2013   100329                    Concord Mine           0       144002
7   2013   100851                  Oak Grove Mine     2269014      1001809
8   2013   102901                Shoal Creek Mine           0        12396
9   2013   102901                Shoal Creek Mine     1453024      1237415
10  2013   103180             Sloan Mountain Mine      327780       196963
11  2013   103182                        Fishtrap      175058        87314
12  2013   103285        

In [161]:
#question 118
import pandas as pd
df=pd.read_excel('C:\\Users\\omkar\\Downloads\\coalpublic2013.xlsx')
print(k)
df[df['Mine_Name'].map(lambda x:x.startswith("P"))].head()

Mine_Name


Year  MSHA ID                      Mine_Name  Production  Labor_Hours
13  2013   103332                  Powhatan Mine      140521        61394
18  2013   102976  Piney Woods Preparation Plant           0        14828
19  2013   102976  Piney Woods Preparation Plant           0        23193
46  2013   103321                 Poplar Springs      189370        76366

In [170]:
#question 119
import pandas as pd
d=pd.read_excel('C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\employee.xlsx')
print(d)

d[d['hire_date'] >='20070101']

    emp_id   first_name   last_name  hire_date
0      100       Steven        King 2003-06-17
1      101        Neena     Kochhar 2005-09-21
2      102          Lex     De Haan 2001-01-13
3      103    Alexander      Hunold 2006-01-03
4      104        Bruce       Ernst 2007-05-21
5      105        David      Austin 2005-06-25
6      106        Valli   Pataballa 2006-02-05
7      107        Diana     Lorentz 2007-02-07
8      108        Nancy   Greenberg 2002-08-17
9      109       Daniel      Faviet 2002-08-16
10     110         John        Chen 2005-09-28
11     111       Ismael     Sciarra 2005-09-30
12     112  Jose Manuel       Urman 2006-03-07
13     113         Luis        Popp 2007-12-07
14     114          Den    Raphaely 2002-12-07
15     115    Alexander        Khoo 2003-05-18
16     116       Shelli       Baida 2005-12-24
17     117        Sigal      Tobias 2005-07-24
18     118          Guy      Himuro 2006-11-15
19     119        Karen  Colmenares 2007-08-10


emp_id first_name   last_name  hire_date
4      104      Bruce       Ernst 2007-05-21
7      107      Diana     Lorentz 2007-02-07
13     113       Luis        Popp 2007-12-07
19     119      Karen  Colmenares 2007-08-10

In [174]:
#question 120
import pandas as pd
df=pd.read_excel('C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\employee.xlsx')
print(d)
df2 = df.set_index(['hire_date'])
result = df2["2005"]
result


    emp_id   first_name   last_name  hire_date
0      100       Steven        King 2003-06-17
1      101        Neena     Kochhar 2005-09-21
2      102          Lex     De Haan 2001-01-13
3      103    Alexander      Hunold 2006-01-03
4      104        Bruce       Ernst 2007-05-21
5      105        David      Austin 2005-06-25
6      106        Valli   Pataballa 2006-02-05
7      107        Diana     Lorentz 2007-02-07
8      108        Nancy   Greenberg 2002-08-17
9      109       Daniel      Faviet 2002-08-16
10     110         John        Chen 2005-09-28
11     111       Ismael     Sciarra 2005-09-30
12     112  Jose Manuel       Urman 2006-03-07
13     113         Luis        Popp 2007-12-07
14     114          Den    Raphaely 2002-12-07
15     115    Alexander        Khoo 2003-05-18
16     116       Shelli       Baida 2005-12-24
17     117        Sigal      Tobias 2005-07-24
18     118          Guy      Himuro 2006-11-15
19     119        Karen  Colmenares 2007-08-10


emp_id first_name last_name
hire_date                              
2005-09-21     101      Neena   Kochhar
2005-06-25     105      David    Austin
2005-09-28     110       John      Chen
2005-09-30     111     Ismael   Sciarra
2005-12-24     116     Shelli     Baida
2005-07-24     117      Sigal    Tobias

In [186]:
#question 121
import pandas as pd
df0=pd.read_excel("C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\employee.xlsx",sheet_name=0)
df1=pd.read_excel("C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\employee.xlsx",sheet_name=1)
df2=pd.read_excel("C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\employee.xlsx",sheet_name=2)
df=pd.concat([df0,df1,df2])
df

emp_id   first_name    last_name  hire_date
0      100       Steven         King 2003-06-17
1      101        Neena      Kochhar 2005-09-21
2      102          Lex      De Haan 2001-01-13
3      103    Alexander       Hunold 2006-01-03
4      104        Bruce        Ernst 2007-05-21
5      105        David       Austin 2005-06-25
6      106        Valli    Pataballa 2006-02-05
7      107        Diana      Lorentz 2007-02-07
8      108        Nancy    Greenberg 2002-08-17
9      109       Daniel       Faviet 2002-08-16
10     110         John         Chen 2005-09-28
11     111       Ismael      Sciarra 2005-09-30
12     112  Jose Manuel        Urman 2006-03-07
13     113         Luis         Popp 2007-12-07
14     114          Den     Raphaely 2002-12-07
15     115    Alexander         Khoo 2003-05-18
16     116       Shelli        Baida 2005-12-24
17     117        Sigal       Tobias 2005-07-24
18     118          Guy       Himuro 2006-11-15
19     119        Karen   Colmenares 2007-08-10
0      120      Matthew        Weiss 2004-07-18
1      121         Adam        Fripp 2005-04-10
2      122        Payam     Kaufling 2003-05-01
3      123       Shanta      Vollman 2005-10-10
4      124        Kevin      Mourgos 2007-11-16
5      125        Julia        Nayer 2005-07-16
6      126        Irene  Mikkilineni 2006-09-28
7      127        James       Landry 2007-01-14
8      128       Steven       Markle 2008-03-08
9      129        Laura       Bissot 2005-08-20
10     130        Mozhe     Atkinson 2005-10-30
11     131        James       Marlow 2005-02-16
12     132           TJ        Olson 2007-04-10
13     133        Jason       Mallin 2004-06-14
14     134      Michael       Rogers 2006-08-26
15     135           Ki          Gee 2007-12-12
16     136        Hazel   Philtanker 2008-02-06
17     137       Renske       Ladwig 2003-07-14
18     138      Stephen       Stiles 2005-10-26
0      141       Trenna         Rajs 2003-10-17
1      142       Curtis       Davies 2005-01-29
2      143      Randall        Matos 2006-03-15
3      144        Peter       Vargas 2006-07-09
4      145         John      Russell 2004-10-01
5      146        Karen     Partners 2005-01-05
6      147      Alberto    Errazuriz 2005-03-10
7      148       Gerald    Cambrault 2007-10-15
8      149        Eleni      Zlotkey 2008-01-29

In [187]:
#question 122
import pandas as pd
df0=pd.read_excel("C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\employee.xlsx",sheet_name=0)
df1=pd.read_excel("C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\employee.xlsx",sheet_name=1)
df2=pd.read_excel("C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\employee.xlsx",sheet_name=2)
df=pd.concat([df0,df1,df2])
df.to_excel("New excel sheet.xlsx")

In [199]:
#question 123
import pandas as pd
import numpy as np
df=pd.read_csv("C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\titanic.csv")
k=pd.pivot_table(df,index=['sex','age'])
l=pd.pivot_table(df,index=['sex','age'],aggfunc=np.sum)
print(l)

              Unnamed: 15  adult_male  alone      fare  parch  pclass  sibsp  survived
sex    age                                                                            
female 0.75           0.0         0.0    0.0   38.5166      2       6      4         2
       1.00           0.0         0.0    0.0   26.8750      3       6      1         2
       2.00           0.0         0.0    0.0  259.4750      9      15      9         2
       3.00           0.0         0.0    0.0   62.6542      3       5      4         1
       4.00           0.0         0.0    0.0  114.1417      6      13      4         5
       5.00           0.0         0.0    1.0   90.8708      5      11      7         4
       6.00           0.0         0.0    0.0   64.2750      3       5      4         1
       7.00           0.0         0.0    0.0   26.2500      2       2      0         1
       8.00           0.0         0.0    0.0   47.3250      3       5      3         1
       9.00           0.0         0.0    0.

In [204]:
#question 124
import numpy as np
df=pd.read_csv("C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\titanic.csv")
l=pd.cut
print(l)

        survived
sex             
female  0.742038
male    0.188908


In [210]:
#question 125
import numpy as np
import panadas as
df=pd.read_csv("C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\titanic.csv")
l = pd.cut(df['age'],[0, 10, 30, 60, 80])
print(l)

0      (10.0, 30.0]
1      (30.0, 60.0]
2      (10.0, 30.0]
3      (30.0, 60.0]
4      (30.0, 60.0]
           ...     
886    (10.0, 30.0]
887    (10.0, 30.0]
888             NaN
889    (10.0, 30.0]
890    (30.0, 60.0]
Name: age, Length: 891, dtype: category
Categories (4, interval[int64]): [(0, 10] < (10, 30] < (30, 60] < (60, 80]]


In [211]:
#question 126
import pandas as pd
import numpy as np
df = pd.read_csv('C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\titanic.csv')
age = pd.cut(df['age'], [0, 20, 55])
result = df.pivot_table('survived', index=['sex', age], columns='class')
print(result)

class               First    Second     Third
sex    age                                   
female (0, 20]   0.928571  1.000000  0.510638
       (20, 55]  0.968750  0.912281  0.407407
male   (0, 20]   0.571429  0.526316  0.197368
       (20, 55]  0.440000  0.054054  0.134503


In [217]:
#question 127
import pandas as pd
import numpy as np
df = pd.read_csv('C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\titanic.csv')
result = df.pivot_table(index=['sex'], columns=['pclass'], aggfunc='count')
print(result)

       Unnamed: 15       adult_male            age          alive           alone           class           deck        embark_town           embarked           fare           parch           sibsp           survived            who          
pclass           1  2  3          1    2    3    1   2    3     1    2    3     1    2    3     1    2    3    1   2  3           1    2    3        1    2    3    1    2    3     1    2    3     1    2    3        1    2    3    1    2    3
sex                                                                                                                                                                                                                                              
female           0  0  0         94   76  144   85  74  102    94   76  144    94   76  144    94   76  144   81  10  6          92   76  144       92   76  144   94   76  144    94   76  144    94   76  144       94   76  144   94   76  144
male             0  0  0        

In [221]:
#question 128
import pandas as pd
import numpy as np
df = pd.read_csv('C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\titanic.csv')
df.pivot_table( 'survived' , [ 'sex' , 'alone' ] , 'class')

class            First    Second     Third
sex    alone                              
female False  0.966667  0.931818  0.416667
       True   0.970588  0.906250  0.616667
male   False  0.425532  0.277778  0.180723
       True   0.333333  0.097222  0.121212

In [225]:
#question 129
import pandas as pd
import numpy as np
df = pd.read_csv('C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\titanic.csv')
df
df.pivot_table( 'survived' , ['class', 'sex', 'alone','embark_town'])

survived
class  sex    alone embark_town          
First  female False Cherbourg    1.000000
                    Queenstown   1.000000
                    Southampton  0.941176
              True  Cherbourg    0.944444
                    Southampton  1.000000
       male   False Cherbourg    0.473684
                    Queenstown   0.000000
                    Southampton  0.407407
              True  Cherbourg    0.347826
                    Southampton  0.326923
Second female False Cherbourg    1.000000
                    Southampton  0.923077
              True  Cherbourg    1.000000
                    Queenstown   1.000000
                    Southampton  0.892857
       male   False Cherbourg    0.166667
                    Southampton  0.300000
              True  Cherbourg    0.250000
                    Queenstown   0.000000
                    Southampton  0.089552
Third  female False Cherbourg    0.611111
                    Queenstown   0.625000
                    Southampton  0.327586
              True  Cherbourg    0.800000
                    Queenstown   0.760000
                    Southampton  0.466667
       male   False Cherbourg    0.500000
                    Queenstown   0.100000
                    Southampton  0.142857
              True  Cherbourg    0.151515
                    Queenstown   0.068966
                    Southampton  0.123762

In [246]:
#question 130
import pandas as pd
df=pd.read_csv("C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\ufo_sighting_data.csv")
df

Date_time                  city state/province country UFO_shape length_of_encounter_seconds described_duration_of_encounter                                        description date_documented    latitude   longitude
0      10-10-1949 20:30            san marcos             tx      us  cylinder                        2700                      45 minutes  This event took place in early fall around 194...       4/27/2004  29.8830556  -97.941111
1      10-10-1949 21:00          lackland afb             tx     NaN     light                        7200                         1-2 hrs  1949 Lackland AFB&#44 TX.  Lights racing acros...      12/16/2005    29.38421  -98.581082
2      10-10-1955 17:00  chester (uk/england)            NaN      gb    circle                          20                      20 seconds  Green/Orange circular disc over Chester&#44 En...       1/21/2008        53.2   -2.916667
3      10-10-1956 21:00                  edna             tx      us    circle                          20                        1/2 hour  My older brother and twin sister were leaving ...       1/17/2004  28.9783333  -96.645833
4      10-10-1960 20:00               kaneohe             hi      us     light                         900                      15 minutes  AS a Marine 1st Lt. flying an FJ4B fighter/att...       1/22/2004  21.4180556 -157.803611
...                 ...                   ...            ...     ...       ...                         ...                             ...                                                ...             ...         ...         ...
80327  09-09-2013 21:15             nashville             tn      us     light                         600                      10 minutes  Round from the distance/slowly changing colors...       9/30/2013     36.1658  -86.784444
80328  09-09-2013 22:00                 boise             id      us    circle                        1200                      20 minutes  Boise&#44 ID&#44 spherical&#44 20 min&#44 10 r...       9/30/2013     43.6136 -116.202500
80329  09-09-2013 22:00                  napa             ca      us     other                        1200                            hour                                       Napa UFO&#44       9/30/2013     38.2972 -122.284444
80330  09-09-2013 22:20                vienna             va      us    circle                           5                       5 seconds  Saw a five gold lit cicular craft moving fastl...       9/30/2013     38.9011  -77.265556
80331  09-09-2013 23:00                edmond             ok      us     cigar                        1020                      17 minutes  2 witnesses 2  miles apart&#44 Red &amp; White...       9/30/2013     35.6528  -97.477778

[80332 rows x 11 columns]

In [260]:
#question 131
import pandas as pd
df=pd.read_csv("C:\\Users\\omkar\\Downloads\\py sub and obj\\py sub and obj\\data for subjective questions\\ufo_sighting_data.csv")

selected_period = df[(df['Date_time'] >= '1950-01-01 00:00:00') & (df['Date_time']<= '1960-12-31 23:59:59')]
print(selected_period)

Empty DataFrame
Columns: [Date_time, city, state/province, country, UFO_shape, length_of_encounter_seconds, described_duration_of_encounter, description, date_documented, latitude, longitude]
Index: []
